server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/francescorosati1993/smarthome-config.git
          clone-on-start: false

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Espone tutti gli endpoint Actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

